name: Kotlin Artifacts Build

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message for manually triggering'
        required: false
        default: 'Triggered for Updates'
        type: string
      publication_type:
        description: 'Select artifact type to publish: aar, jar, or both'
        required: true
        default: both
        type: string

jobs:
  maven-publish:
    if: "${{ !contains(github.ref, 'master') }}"
    uses: mosip/kattu/.github/workflows/maven-publish-android.yml@master
    with:
      SERVICE_LOCATION: 'kotlin'
      ANDROID_SERVICE_LOCATION: 'PixelPass'
      JAVA_VERSION: 21
      LICENSE_NAME: 'MPL-2.0'
      PUBLICATION_TYPE: ${{ inputs.publication_type }}
    secrets:
      OSSRH_USER: ${{ secrets.OSSRH_USER }}
      OSSRH_URL: ${{secrets.OSSRH_SNAPSHOT_URL }}
      OSSRH_SECRET: ${{ secrets.OSSRH_SECRET }}
      OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
      GPG_SECRET: ${{ secrets.GPG_SECRET }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_INJI_TEAM }}
